komorebi/urls.py
from django.contrib import admin
from django.urls import path

import manageImages
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

from komorebi import views

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('admin/', admin.site.urls),
    path('login/', include('manageUsers.urls')),
    path('images/', include('manageImages.urls')),
    path('', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manageImages/urls.py
from django.urls import path, include
from . import views

app_name = "manageImages"

urlpatterns = [
    path('closeup/<ID>/', views.closeup, name='closeup'),
    path('addimage/', views.addImage.as_view(), name='addimage'),
    path('like_picture/', views.LikePictureView.as_view(), name='like_picture'),
    path('dislike_picture/', views.DislikePictureView.as_view(), name='dislike_picture'),
    path('deletepicture/<imageID>', views.imagedelete, name='picturedelete'),
]

manageUsers/urls.py
from django.urls import path, include,re_path
from . import views
from django.contrib.auth.views import LogoutView
from django.contrib import admin

app_name = "manageUsers"

urlpatterns = [
    path('myfeed/', views.myfeed, name='myfeed'),
    path("logout/", LogoutView.as_view(), name="logout"),
    path('', views.login, name='login'),
    path('create/', views.create.as_view(), name='create'),
    path('googlecreate/', views.googlecreate.as_view(), name='googlecreate'),
    path('edit/', views.edit.as_view(), name='edit'),
    path('profile/<username>/', views.profile, name='profile'),
    path('follow/', views.follow.as_view(), name='follow'),
    path('deleteuser/', views.userdelete, name='userdelete'),
]

templates/addImage.html
{% extends 'basepage.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title_block %}
    Add Image
{% endblock %}

{% block subtitle_block %}
    Add Image
{% endblock %}

{% block body_block %}
        <div class="row justify-content-center lightText-White pt-3 ">
            <div class="col-lg-6" id="formDiv">
                <div class="row-lg-10 mx-3">
                    <h1 class="lightText-White pt-4" align="center">Add Image</h1>
                  <form method="POST" enctype="multipart/form-data">
                      {% csrf_token %}
                        {% load crispy_forms_tags %}
                        {% crispy form %}
                      <div class="pt-3"></div>
                  </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/base-page.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <link rel="icon" type="image/x-icon" href="{% static 'icons/favicon.png' %}">
    <link href="{% static 'styles.css' %}" rel="stylesheet" type="text/css">
    {% block scriptblock %}
    {% endblock %}

    <meta charset="UTF-8">
    <style>
        {% block styleblock %}
        {% endblock %}

        #navigation-rule {
            color: #a024ff;
            height: 3px;
        }

        #quote-rule {
            color: #a024ff;
            height: 2px;
            margin-top: 2px;
            margin-bottom: 2px;
        }

        #quote-title {
            font-size: 30px;
            color: #a024ff;
        }

        .inlist {
            border-right: 2px solid #a024ff;
        }

    </style>


    <title>
        komorebi -
        {% block title_block %}
        {% endblock %}
    </title>
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static "js/manageImage-AJAX.js" %}"></script>

</head>

<body>

<div class="container">
    <div class="row justify-content-between pt-3">
        <div title class="col-xs-12 col-md-4 p-3 ">
            <div id="title" class="row">komorebi</div>
            <div id="subtitle" class="row">{{ title }}</div>
            {% if user.is_authenticated %}
                <div id="userGreeting" class="row">Hello {{ user.get_username }}! <a href="/login/logout/"
                                                                                     style="padding-left: 0px">Logout</a>
                </div>
            {% else %}
                <div id="userGreeting" class="row"><a href="{% url 'login' %}"
                                                      style="padding-left: 0px;padding-right: 0px;text-decoration: inherit;">Login</a>
                    or <a href="{% url 'manageUsers:create' %}" style="padding-left: 0px;text-decoration: inherit;">Create
                        Account</a></div>
            {% endif %}


        </div>
        <div ng-view class="col-lg-3 p-3 col-xs-5">
            <div id="quote-title" class="row justify-content-center">Quote of the Day</div>
            <div class="row justify-content-center">
                <div class="col-6">
                    <hr id="quote-rule">
                </div>
            </div>
            <div id="quote" class="row text justify-content-center">Serenity is not freedom from the storm, but calm
                within the storm
            </div>
        </div>
    </div>
    <hr id="navigation-rule">
    <div class="row justify-content-center">
        {% if request.get_full_path != "/home/" %}
            <div class="col-4 col-lg-2 inlist">
                <div class="navigation row lightText-Gray justify-content-center"><a style="text-align: center; text-decoration: none;
            color: inherit;" href="{% url 'home' %}" onMouseOver="this.style.color='#a024ff'"
                                                                                     onMouseOut="this.style.color='black'">Home</a>
                </div>
            </div>
        {% endif %}
        {% if request.get_full_path != "/about/" %}
            <div class="col-4 col-lg-2 inlist">
                <div class="navigation row lightText-Gray justify-content-center"><a style="text-align: center; text-decoration: none;
            color: inherit;" href="{% url 'about' %}" onMouseOver="this.style.color='#a024ff'"
                                                                                     onMouseOut="this.style.color='black'">About</a>
                </div>
            </div>
        {% endif %}
        {% if user.is_authenticated %}
            {% if request.get_full_path != "/myfeed/" %}
                <div class="col-4 col-lg-2">
                    <div class="navigation row lightText-Gray justify-content-center"><a style="text-align: center; text-decoration: none;
                color: inherit;" href="{% url 'manageUsers:myfeed'%}" onMouseOver="this.style.color='#a024ff'"
                                                                                         onMouseOut="this.style.color='black'">My
                        Feed</a></div>
                </div>
            {% endif %}
            {% if request.get_full_path != "/login/profile/{{ request.user.username }}/" %}
                <div class="col-4 col-lg-2" style="border-left: 2px solid #a024ff;">
                    <div class="navigation row lightText-Gray justify-content-center"><a style="text-align: center; text-decoration: none;
                color: inherit;" href="{% url 'manageUsers:profile' user.get_username%}"
                                                                                         onMouseOver="this.style.color='#a024ff'"
                                                                                         onMouseOut="this.style.color='black'">My
                        Profile</a>
                    </div>
                </div>
            {% endif %}
        {% else %}
            {% if request.get_full_path != "/create/" %}
                <div class="col-4 col-lg-2" >
                    <div class="navigation row lightText-Gray justify-content-center"><a style="text-align: center; text-decoration: none;
                color: inherit;" href="{% url 'manageUsers:create' %}" onMouseOver="this.style.color='#a024ff'"
                                                                                         onMouseOut="this.style.color='black'">Create
                        Account</a></div>
                </div>
            {% endif %}
        {% endif %}
        {% block body_block %}
        {% endblock %}
    </div>

</div>


</div>


</body>

</html>

templates/closeup.html
{% extends 'base-page.html' %}
{% load static %}
{% load staticfiles %}

{% block title_block %}
Image Close Up
{% endblock %}

{% block subtitle_block %}
Image Close Up
{% endblock %}

{% block styleblock %}
.card-body{
    background-color: white;
}
#author{
    colour: black;
    text-decoration: inherit;
    font-size: 25px;
}
{% endblock %}

{% block body_block %}
<div class="row justify-content-center">
    <div style="width : 60%;" class="card mt-3 px-0">
        <img src="{{ picture.image.url }}" class="card-img-top " style="width: 100%;
    height: 45vw;
    object-fit: cover;" alt="...">
        <div class="card-body">
            <div class="row">
                <div class="col-6">
                    <h5 class="card-title lightText-Purple" style="font-size: 35px">{{ picture.name }}</h5>
                </div>
                <div class="col-6">
                    {% if user.is_authenticated %}
                    <button type="button"
                            data-pictureID="{{ picture.ID }}"
                            class="btn btn-default btn-sm likeButton">
                        <img src="{% static 'icons/purpleLike.png' %}" width="35">
                        <div style="display:inline;color: #a024ff;font-size: 20px;" class="p-1"
                             id="like-count{{ picture.ID }}">{{ picture.likes.count }}</div>
                    </button>
                    <button type="button"
                            data-pictureID="{{ picture.ID }}"
                            class="btn btn-default btn-sm dislikeButton">
                        <img src="{% static 'icons/purpleDislike.png' %}" width="35">
                        <div style="display:inline;color: #a024ff;font-size: 20px;" class="p-1"
                             id="dislike-count{{ picture.ID }}">{{ picture.dislikes.count }}</div>
                    </button>
                    {% else %}
                        <button type="button"
                            data-pictureID="{{ picture.ID }}"
                            class="btn btn-default btn-sm dummyButton">
                        <img src="{% static 'icons/purpleLike.png' %}" width="35">
                        <div style="display:inline;color: #a024ff;font-size: 20px;" class="p-1"
                             id="like-count{{ picture.ID }}">{{ picture.likes.count }}</div>
                    </button>
                    <button type="button"
                            data-pictureID="{{ picture.ID }}"
                            class="btn btn-default btn-sm dummyButton">
                        <img src="{% static 'icons/purpleDislike.png' %}" width="35">
                        <div style="display:inline;color: #a024ff;font-size: 20px;" class="p-1"
                             id="dislike-count{{ picture.ID }}">{{ picture.dislikes.count }}</div>
                    </button>
                    {% endif %}
                    <button type="button"
                            data-pictureID="{{ picture.ID }}"
                            class="btn btn-default btn-sm shareButton">
                        <img src="{% static 'icons/share.png' %}" width="35">
                        <div style="display:inline;color: #a024ff;font-size: 20px;" class="p-1"
                             id="shareButton">Share
                        </div>
                    </button>

                </div>
                <a href="{% url 'manageUsers:profile' picture.uploadedBy.username %}" class="d-inline-flex lightText-Gray" id="author">
                    Posted By: {{ picture.uploadedBy.username }}
                </a>
                {% if picture.uploadedBy.username == user.get_username %}
                    <a href="{% url 'manageImages:picturedelete' picture.ID %}" class="btn btn-primary btn-lg mt-3 delete-button" role="button" aria-disabled="true">DELETE PICTURE</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/edit-user.html
<!DOCTYPE html>
{% extends 'base-page.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title_block %}
    Edit Account
{% endblock %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        {% block styleblock %}
            #formDiv {
                background-color: #a024ff;
                border-radius: 20px;
                color: white;
                font-size: 20px;
            }

            .submitButton {
                margin-left: 30px;
                margin-bottom: 30px;
                width:150px;
                display:block !important;
                background-color: white !important;
                color: #a024ff !important;
            }

            #delete-button{
                background-color: red;
            }

        {% endblock %}

    </style>

</head>
<body>
{% block body_block %}
        <div class="row justify-content-center lightText-White pt-3">
            <div class="col-lg-6" id="formDiv">
                <div class="row-lg-10 mx-3">
                    <h1 class="lightText-White pt-4" align="center">Create Account</h1>

                   <form method="post" enctype="multipart/form-data">
                      {% csrf_token %}
                        {% load crispy_forms_tags %}
                        {% crispy form %}
                        <a href="{% url 'manageUsers:userdelete' %}" class="btn btn-primary btn-lg mt-3 delete-button"  role="button" aria-disabled="true">DELETE ACCOUNT</a>
                      <div class="pt-3"></div>
                  </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>

templates/editUser.html
{% extends 'basePage.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title_block %}
    Edit Account
{% endblock %}

{% block subtitle_block %}
    Edit Account
{% endblock %}

{% block body_block %}
        <div class="row justify-content-center lightText-White pt-3">
            <div class="col-lg-6" id="formDiv">
                <div class="row-lg-10 mx-3">
                    <h1 class="lightText-White pt-4" align="center">Edit Account</h1>

                   <form method="post" enctype="multipart/form-data">
                      {% csrf_token %}
                        {% load crispy_forms_tags %}
                        {% crispy form %}
                        <a href="{% url 'manageUsers:userdelete' %}" class="btn btn-primary btn-lg mt-3 delete-button"  role="button" aria-disabled="true">DELETE ACCOUNT</a>
                      <div class="pt-3"></div>
                  </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>

templates/home.html
<!DOCTYPE html>
{% extends 'base-page.html' %}
{% load static %}

{% block title_block %}
    Home
{% endblock %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        {% block styleblock %}
            .card:hover {
                transition: transform 250ms;
                transform: scale(1.03);
            }

            .navigation-container{
                border-right: 2px solid #a024ff;
            }

            .navigation-link{
                text-align: center !important;
                text-decoration: none !important;
                color: inherit !important;
            }

            #navigation{
                text-align: center !important;
                text-decoration: none !important;
                color: inherit !important;
            }

            #post-image{
                width: 100%;
                height:330px;
                object-fit: cover;
            }

            .button-text{
                display:inline;
                color: white;
                font-size: 18px;
            }

        {% endblock %}

    </style>

</head>


<body>
<div class="container">
{% block body_block %}
    <div class="row justify-content-center pt-lg-1 g-0">
        <div class="col-sm-12 col-md-10 pt-3">
            <div class="row g-0">
                {% for picture in pictures %}
                    <div class="col-xs-12 col-lg-4 pt-1 pt-lg-0 ">
                        <div class="card mx-lg-1 mx-xs-auto mt-2 hover-shadow" >
                            <a href="{% url 'manageImages:closeup' picture.ID %}" class="stretched-link">
                                <div class="bg-image hover-zoom">
                                    <img id="post-image" src={{ picture.thumbnail.url }} class="card-img-top" alt="...">
                                </div>

                            </a>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-5">
                                        <h5 class="card-title p-2">{{ picture.name }}</h5>
                                    </div>
                                    <div class="col-7">
                                        {% if user.is_authenticated %}
                                        <button type="button"
                                                data-pictureID="{{ picture.ID }}"
                                                class="btn btn-default btn-sm likeButton">
                                            <img src="/static/icons/whiteLike.png" width="35">
                                            <div class="p-1 button-text"
                                                 id="like-count{{ picture.ID }}">{{ picture.likes.count }}</div>
                                        </button>
                                        <button type="button"
                                                data-pictureID="{{ picture.ID }}"
                                                class="btn btn-default btn-sm dislikeButton">
                                            <img src="/static/icons/whiteDislike.png" width="35">
                                            <div class="p-1 button-text"
                                                 id="dislike-count{{ picture.ID }}">{{ picture.dislikes.count }}</div>
                                        </button>
                                        {% else %}
                                            <button type="button"
                                                data-pictureID="{{ picture.ID }}"
                                                class="btn btn-default btn-sm dummyButton">
                                            <img src="/static/icons/whiteLike.png" width="35">
                                            <div class="p-1 button-text"
                                                 id="like-count{{ picture.ID }}">{{ picture.likes.count }}</div>
                                        </button>
                                        <button type="button"
                                                data-pictureID="{{ picture.ID }}"
                                                class="btn btn-default btn-sm dummyButton">
                                            <img src="/static/icons/whiteDislike.png" width="35">
                                            <div class="p-1 button-text"
                                                 id="dislike-count{{ picture.ID }}">{{ picture.dislikes.count }}</div>
                                        </button>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

</body>
{% endblock %}
</html>

templates/my-feed.html
<!DOCTYPE html>
{% extends 'base-page.html' %}
{% load static %}


{% block title_block %}
    My Feed
{% endblock %}


<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        {% block styleblock %}

            .card:hover {
                transition: transform 250ms;
                transform: scale(1.03);
            }


        .card {
            border-radius: 20%;
            cursor: pointer;
        }

        .card-body {
            background-color: #a024ff;
            font-family: 'hk_grotesklight';
            color: white;
        }

        .card .btn {
            z-index: 2;
            position: relative;
        }

        #post-image{
            width: 100%;
            height:330px;
            object-fit: cover;
        }

        .button-text{
            display:inline;
            color: white;
            font-size: 18px;
        }

        #no-likes{
            text-align: center;
            color: #a024ff;
            font-family: 'hk_grotesklight';
            font-size: 25px;
        }

        {% endblock %}

    </style>

</head>


<body>
<div class="container">
{% block body_block %}
    <div class="row justify-content-center pt-lg-1 g-0">
        <div class="col-sm-12 col-md-10 pt-3">
            <div class="row g-0">

                {% if not pictures %}
                    <div id="no-likes" class="pt-5">You need to like at least 5 images before we can curate your feed!</div>
                {% else %}

                {% for picture in pictures %}

                    <div class="col-xs-12 col-lg-4 pt-1 pt-lg-0 ">
                        <div class="card mx-lg-1 mx-xs-auto mt-2">
                            <a href="{% url 'manageImages:closeup' picture.ID %}" class="stretched-link">
                                <img id="post-image" src={{ picture.thumbnail.url }} class="card-img-top" alt="...">
                            </a>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-5">
                                        <h5 class="card-title p-2">{{ picture.name }}</h5>
                                    </div>
                                    <div class="col-7">
                                        <button type="button"
                                                data-pictureID="{{ picture.ID }}"
                                                class="btn btn-default btn-sm likeButton">
                                            <img src="/static/icons/whiteLike.png" width="35">
                                            <div class="p-1 button-text"
                                                 id="like-count{{ picture.ID }}">{{ picture.likes.count }}
                                            </div>
                                        </button>
                                        <button type="button"
                                                data-pictureID="{{ picture.ID }}"
                                                class="btn btn-default btn-sm dislikeButton">
                                            <img src="/static/icons/whiteDislike.png" width="35">
                                            <div class="p-1 button-text"
                                                 id="dislike-count{{ picture.ID }}">{{ picture.dislikes.count }}
                                            </div>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
            </div>
        </div>
    </div>
</div>

</body>
{% endblock %}
</html>

templates/myFeed.html
<!DOCTYPE html>
{% extends 'basePage.html' %}
{% load static %}


{% block title_block %}
    My Feed
{% endblock %}


<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        {% block styleblock %}

            .card:hover {
                transition: transform 250ms;
                transform: scale(1.03);
            }


        .card {
            border-radius: 20%;
            cursor: pointer;
        }

        .card-body {
            background-color: #a024ff;
            font-family: 'hk_grotesklight';
            color: white;
        }

        .card .btn {
            z-index: 2;
            position: relative;
        }

        #post-image{
            width: 100%;
            height:330px;
            object-fit: cover;
        }

        .button-text{
            display:inline;
            color: white;
            font-size: 18px;
        }

        #no-likes{
            text-align: center;
            color: #a024ff;
            font-family: 'hk_grotesklight';
            font-size: 25px;
        }

        {% endblock %}

    </style>

</head>


<body>
<div class="container">
{% block body_block %}
    <div class="row justify-content-center pt-lg-1 g-0">
        <div class="col-sm-12 col-md-10 pt-3">
            <div class="row g-0">

                {% if not pictures %}
                    <div id="no-likes" class="pt-5">You need to like at least 5 images before we can curate your feed!</div>
                {% else %}

                {% for picture in pictures %}

                    <div class="col-xs-12 col-lg-4 pt-1 pt-lg-0 ">
                        <div class="card mx-lg-1 mx-xs-auto mt-2">
                            <a href="{% url 'manageImages:closeup' picture.ID %}" class="stretched-link">
                                <img id="post-image" src={{ picture.thumbnail.url }} class="card-img-top" alt="...">
                            </a>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-5">
                                        <h5 class="card-title p-2">{{ picture.name }}</h5>
                                    </div>
                                    <div class="col-7">
                                        <button type="button"
                                                data-pictureID="{{ picture.ID }}"
                                                class="btn btn-default btn-sm likeButton">
                                            <img src="/static/icons/whiteLike.png" width="35">
                                            <div class="p-1 button-text"
                                                 id="like-count{{ picture.ID }}">{{ picture.likes.count }}
                                            </div>
                                        </button>
                                        <button type="button"
                                                data-pictureID="{{ picture.ID }}"
                                                class="btn btn-default btn-sm dislikeButton">
                                            <img src="/static/icons/whiteDislike.png" width="35">
                                            <div class="p-1 button-text"
                                                 id="dislike-count{{ picture.ID }}">{{ picture.dislikes.count }}
                                            </div>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
            </div>
        </div>
    </div>
</div>

</body>
{% endblock %}
</html>

templates/myfeed.html
{% extends 'basePage.html' %}
{% load static %}
{% load staticfiles %}

{% block title_block %}
My Feed
{% endblock %}

{% block subtitle_block %}
My Feed
{% endblock %}

{% block body_block %}
<div>
    <h2 style="font-size: 40px; color: #a024ff;">Recommended Pictures for You</h2>
</div>
{% if myfeed_pictures == None %}
<div>
    <p style="font-size: 25px; color: #a024ff;">You need to like at least 5 pictures to be recommended pictures here!</h2>
</div>
{% elif myfeed_pictures == "empty" %}
<div>
    <p style="font-size: 25px; color: #a024ff;">There are currently no pictures for us to recommend. Sorry...</h2>
</div>
{% else %}
<div class="row justify-content-center pt-lg-1 g-0">
    <div class="col-sm-12 col-md-10">
        <div class="row g-0">
            {% for picture in myfeed_pictures %}
                <div class="col-xs-12 col-lg-4 pt-1 pt-lg-0 ">
                    <div class="card mx-lg-1 mx-xs-auto mt-2">
                        <a href="{% url 'manageImages:closeup' picture.ID %}" class="stretched-link">
                            <img src={{ picture.thumbnail.url }} class="card-img-top" alt="..."
                                 style="width: 100%; height:330px; object-fit: cover;">
                        </a>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-5">
                                    <h5 class="card-title p-2">{{ picture.name }}</h5>
                                </div>
                                <div class="col-7">
                                    <button type="button"
                                            data-pictureID="{{ picture.ID }}"
                                            class="btn btn-default btn-sm likeButton">
                                        <img src="/static/icons/whiteLike.png" width="35">
                                        <div style="display:inline;color: white;font-size: 18px;" class="p-1"
                                             id="like-count{{ picture.ID }}">{{ picture.likes.count }}</div>
                                    </button>
                                    <button type="button"
                                            data-pictureID="{{ picture.ID }}"
                                            class="btn btn-default btn-sm dislikeButton">
                                        <img src="/static/icons/whiteDislike.png" width="35">
                                        <div style="display:inline;color: white;font-size: 18px;" class="p-1"
                                             id="dislike-count{{ picture.ID }}">{{ picture.dislikes.count }}</div>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endif %}
{% endblock %}